### ISSUE TITLE
URB: Tracking

### ISSUE THREAD

**Issue by jvhoven** [urbinn/urbinn#108]
- [x] Extract orbs from left and right image
- [x] Match points in left and right image
- [x] Correct this by doing subpixel matching (or do this before matching the points)
- [x] Use triangulation to estimate depth for a given keypoint
- [x] Use a vertical 'canny edge' filter to find vertical edges and use the endpoints as key-points.
- [x] g2o hooks voor python maken
- [x] motion only bundle adjustment maken over 2 frames.
- [ ] problemen met stereo estimation verhelpen
- [ ] problemen met frame tracking verhelpen

**Comment by jeroenvuurens** [comment]
Subpixel matching gebeurt als volgt:
Elke ORB is een patch rond een keypoint, bv 9x9 pixels
pixel-estimate: probeer verschillende x-verplaatsingen uit en zoek het x-verplaatsing waarop de verschil tussen de linker en rechter patch minimaal is.
subPixel estimate kun je snel berekenen vanuit je pixel estimate, ORB gebruikt daarvoor de techniek beschreven in http://mccormickml.com/2014/01/10/stereo-vision-tutorial-part-i/

**Comment by jeroenvuurens** [comment]
Het inschatten van de afstand lijkt goed te gaan. We hebben getest op kleine afstand op een stoel en koffiebeker, wat aardig klopt. Op het eerste frame van KITTI lijken de afstanden ook behoorlijk te kloppen.

**Comment by jeroenvuurens** [comment]
Inspectie van de ORB2 code laat zien dat nauwelijks wordt gecheckt of orbs tussen plaatje wel goede matches zijn, waar waarschijnlijk veel noise vandaan komt. Als tegenhanger gebruiken we alleen ORBs in het linker plaatje en proberen een patch rechts te vinden die een betrouwbare match is. De betrouwbaarheid wordt getest door te kijken of we net elder op dezelfde rij een plek hebben waar de patch bijna net zo goed past. Met een threshold nextBestDistance/bestDistance > 1.4 houden we alleen de 101 keypoints over waarvoor dat geldt, wat op het oog goede keypoints lijken te zijn. zie /data/urbinn/notebooks/urb/stereo_matching_j_leftorb.ipynb

**Comment by jeroenvuurens** [comment]
Een probleem met de ORBs is dat ze noisy zijn en dat er meer zwakke dan sterke keypoints uit komen. Als alternatief gaan we kijken naar een vertical 'canny edge' filter. Het idee is dat we het begin en eindpunt van canny edges nemen als keypoint. Deze kenpoints hebben een grote kans een bruikbaar punt te zijn omdat er een verticale edge is, het is waarschijnlijk een stuk sneller en het zorgt misschien voor een beter spreiding van keypoints over de image.

**Comment by jvhoven** [comment]
Voor het onderdeel bundle adjustment hebben we gekeken naar een voorbeeld van g2o. Daarnaast hadden we een artikel gevonden die een uitleg van het voorbeeld geeft. Allereerst hebben we de demo geprobeerd te runnen; dit bleek goed te werken.

---

Omdat URB geschreven is in Python zijn er Python hooks nodig naar g2o. Deze moeten we zelf maken omdat er geen beschikbare code is die dit voor ons doet. Na een lange dag proberen konden we uiteindelijk het g2o bundle adjustment voorbeeld aanroepen via een Python methode met behulp van Boost Python. Toen we probeerde na te maken op een andere laptop liepen we vervolgens weer tegen problemen aan. Uiteindelijk is de beslissing genomen om de oplossing te realiseren in Docker zodat we de productie omgeving kunnen nabootsen. 

--- 

De repository is geconfigureerd voor Docker en er zijn stappen ondernomen om de werkende versie van het bundle adjustment voorbeeld dat aangeroepen kon worden via Boost Python over te zetten in de Docker omgeving. Na veel testen en uitproberen lopen we vast op een segmentation fault bij het aanroepen van `g2o::VertexSE3Expmap`.

**Comment by jeroenvuurens** [comment]
Er staat een dump van de eerste 10 frames van KITTI sequence 0. Ik heb er maar 10 gedaan omdat in het 10e frame nog maar iets van 20 punten uit et eerste frame te zien zijn. Mogelijk wordt het slechter als je te weinig punten overlapt.

Het script met uitleg van de dump staat in urb/sequence1911/match_sequence.ipynb en de dump zelf staat in urb/sequence1911/dump

Mogelijk zijn de resultaten al vrij aardig, hangt er vanaf of g2o gevoelig is voor outliers of niet (ik denk het niet omdat ORB2 ook veel outlier genereerd). Maar we kunnen later kijken of we ouliers kunnen verwijderen en eventueel meer punten toevoegen.

In ORB2 zag ik dat in Optimizer.cc de hele g2o code staat waarmee ze bijvoorbeeld motion only bundle adjustment aanroepen op g2o, dus dat is denk ik handig om naar te gaan kijken.

**Comment by jvhoven** [comment]
De bundle adjustment demo is aangepast maar is volgens mij niet geheel correct gegaan; het positieve is dat er output gegeven wordt. 

```Performing full BA:
iteration= 0	 chi2= 1122365245.058670	 time= 0.0083517	 cumTime= 0.0083517	 edges= 276	 schur= 1	 lambda= 3563843814.182687	 levenbergIter= 1
iteration= 1	 chi2= 987399084.665882	 time= 0.0055598	 cumTime= 0.0139115	 edges= 276	 schur= 1	 lambda= 1187947938.060895	 levenbergIter= 1
iteration= 2	 chi2= 761669720.443643	 time= 0.0054168	 cumTime= 0.0193283	 edges= 276	 schur= 1	 lambda= 395982646.020298	 levenbergIter= 1
iteration= 3	 chi2= 539224165.580171	 time= 0.0066233	 cumTime= 0.0259516	 edges= 276	 schur= 1	 lambda= 131994215.340099	 levenbergIter= 1
iteration= 4	 chi2= 380387782.905433	 time= 0.0059223	 cumTime= 0.0318739	 edges= 276	 schur= 1	 lambda= 43998071.780033	 levenbergIter= 1
iteration= 5	 chi2= 222253374.715087	 time= 0.0080993	 cumTime= 0.0399732	 edges= 276	 schur= 1	 lambda= 14666023.926678	 levenbergIter= 1
iteration= 6	 chi2= 96726990.032895	 time= 0.0055803	 cumTime= 0.0455535	 edges= 276	 schur= 1	 lambda= 4888674.642226	 levenbergIter= 1
iteration= 7	 chi2= 36995829.766533	 time= 0.0056473	 cumTime= 0.0512008	 edges= 276	 schur= 1	 lambda= 1629558.214075	 levenbergIter= 1
iteration= 8	 chi2= 14760654.632802	 time= 0.0056747	 cumTime= 0.0568755	 edges= 276	 schur= 1	 lambda= 543186.071358	 levenbergIter= 1
iteration= 9	 chi2= 4894215.686006	 time= 0.0070873	 cumTime= 0.0639628	 edges= 276	 schur= 1	 lambda= 181062.023786	 levenbergIter= 1
iteration= 10	 chi2= 1156415.336205	 time= 0.0059311	 cumTime= 0.0698939	 edges= 276	 schur= 1	 lambda= 60354.007929	 levenbergIter= 1
iteration= 11	 chi2= 412691.434676	 time= 0.0055115	 cumTime= 0.0754054	 edges= 276	 schur= 1	 lambda= 20118.002643	 levenbergIter= 1
iteration= 12	 chi2= 240364.543476	 time= 0.0055107	 cumTime= 0.0809161	 edges= 276	 schur= 1	 lambda= 6706.000881	 levenbergIter= 1
iteration= 13	 chi2= 106913.244121	 time= 0.0053236	 cumTime= 0.0862397	 edges= 276	 schur= 1	 lambda= 2235.333627	 levenbergIter= 1
iteration= 14	 chi2= 25245.160051	 time= 0.0054502	 cumTime= 0.0916899	 edges= 276	 schur= 1	 lambda= 745.111209	 levenbergIter= 1
iteration= 15	 chi2= 3120.795207	 time= 0.0054027	 cumTime= 0.0970926	 edges= 276	 schur= 1	 lambda= 248.370403	 levenbergIter= 1
iteration= 16	 chi2= 540.824858	 time= 0.0059337	 cumTime= 0.103026	 edges= 276	 schur= 1	 lambda= 82.790134	 levenbergIter= 1
iteration= 17	 chi2= 291.750275	 time= 0.0059382	 cumTime= 0.108964	 edges= 276	 schur= 1	 lambda= 27.596711	 levenbergIter= 1
iteration= 18	 chi2= 265.389786	 time= 0.0071357	 cumTime= 0.1161	 edges= 276	 schur= 1	 lambda= 9.198904	 levenbergIter= 1
iteration= 19	 chi2= 263.653576	 time= 0.0054076	 cumTime= 0.121508	 edges= 276	 schur= 1	 lambda= 3.066301	 levenbergIter= 1

Point error before optimisation (inliers only): 2.36082
Point error after optimisation (inliers only): 0.958923

POSE:
	 1  0  0 -1
 0  1  0  0
 0  0  1  0
 0  0  0  1

POSE:
	           1 -8.42311e-07   3.3228e-07    -0.959803
 8.42311e-07            1 -6.14677e-07  0.000910978
-3.32279e-07  6.14677e-07            1  0.000119695
           0            0            0            1

POINT:
	0
0
0
POINT:
	-0.000441763
  0.00757048
  -0.0517657
POINT:
	429.165
 26.075
28.6151
POINT:
	684.233
29.0662
15.2807
POINT:
	 382.14
31.9282
27.9479
```

Ik heb de meeste checks er voor nu uitgehaald; namelijk het optellen van observaties en het filteren van outliers. De ORB_SLAM2 aanpak wijkt af van de demo door geen gebruik te maken van `g2o::CameraParameters`. De poses van de frames kloppen ook nog niet omdat het algoritme ervan uitgaat dat er geschatte poses meegegeven worden. Deze stap hebben wij nog niet doorlopen. Er zijn nog een aantal aanpassingen nodig voordat we daadwerkelijk kunnen nagaan of de output hiervan klopt.

**Comment by jeroenvuurens** [comment]
OrbSlam heeft zelf een uitbredeiding gemaakt op g2o met een paar nieuwe klasses die motion only BA doet. Het is verreweg het makkelijkst om die code gewoon over te nemen. Dat betekent dat die code moet worden gecompileerd in g2o. Het gaat denken we alleen om types_six_dof_expmap.cpp en de bijbehorende header file.

Als we die gecompileerd hebben dan kunnen we motion only BA uitvoeren door de camera coordinates te vertalen naar world coordinates. Het gaat om de functie PoseOptimization in de file Optimizer.cc. We hebben alle data die gebruikt wordt gecheckt. De fx fy cx cy komen uit de calibration file. De auteur van ORB heeft die zelf bepaalt en zijn per kitti sequence blijkbaar anders. Ze staan in de YAML files bij de examples. Voor de Zed camera hebben we die waarden in de calibration file.

Dus om het te laten werken moet eigenlijk de docker worden aangepast zodat de aangepaste g2o files erin staan en dan opnieuw compileren.

**Comment by jeroenvuurens** [comment]
Op GitHub staat een nieuwe repo urbinn/urbba met daarin de url versie van motion-only BA. Die kun je compilen als pybind11, g2o en sparsesuite geïnstalleerd zijn.

**Comment by jeroenvuurens** [comment]
Op GitHub staat ook een nieuwe repo urbinn/pyurb met daarin het voorlopige framework om vanuit python frame tracking te doen. Voor het uitvoeren moet urbg2o.so in de folder staan, die kun je linken vanaf de server (/data/urbinn/urbba/build/urbg2o.so) of de urbba repo clonen en zelf compileren.

**Comment by jeroenvuurens** [comment]
Zoals vandaag aangegeven is er een probleem met de pose estimation. Vooral in een bocht met weinig 'vaste' herkenningspunten levert het stereo-matching algoritme te weinig betrouwbare punten op om een pose estimation te kunnen doen.

**Comment by jeroenvuurens** [comment]
Een lastige passage is bijvoorbeeld in KITTI sequence 00 frames 200-212. De auto gaat daar de bocht om en afhankelijk van de instellingen lukt het urb tracking niet om een pose voor ca. 6 frames te berekenen
Een paar eenvoudige experimenten laten zien dat de matching aanzienlijk verbetert door:
- smoothing te verlagen van 5x5 naar 3x3 (waarschijnlijk verhoogd dat de confidence van een match)
- een grotere patch size (bv 30 ipv 17 lijkt accuratere punten op te leveren)
- een lagere confidence threshold voor stereo matching (i.e. een patch tussen linker en rechter plaatje) bv 1.4 ipv 1.8 (hou je meer punten over)
- een hogere confidence threshold voor sequence matching (i.e. een patch tussen keyframe en volgende frame, accuratere match) bv 1.6

smoothing 3x3, patch size 17, en stereo confidence 1.6 en sequence confidence 1.6 gaat zonder problemen door de sequence heen. met een grotere patch size en een lagere stereo confidence lijken de resultaten op het oog iets beter en is het wellicht wat robuuster, maar het wordt wel langzamer en misschien worden kleine afwijking er door local BA ook uitgehaald.

**Comment by jeroenvuurens** [comment]
Stereo tracking is stabiel over de eerste 250 frames van KITTI. Is wel een stuk langzamer, duurt een minuut of 9. De pose estimation van het volgende frame gaat nog niet optimaal. Dat kunnen we voor een groot deel repareren als we detecteren wanneer het mis gaat. Op dit moment wordt alleen gekeken naar het aantal punten dat overblijft nadat motion-only BA outliers heeft verwijderd. 

Een nieuwe verbetering is door ook te kijken of snelheid en rotatiesnelheid redelijke waarden hebben. Test uitgevoerd met limiet op snelheid kan niet groter dan 0 zijn (dan rijden we achteruit) en groter dan 2 (dan rijden we 75km/h.

**Comment by jeroenvuurens** [comment]
We sluiten urb tracking voor nu af. De sequences 00 t/m 10 van KITTI zijn gerund en alleen Seq 01 lijkt problemen te tonen die niet met BA opgelost kunnen worden. Er zijn aparte tickets aangemaakt om Seq 01 te analyseren en BA toe te passen.
